# Generated by Django 5.1.6 on 2025-02-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setoo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
