# Generated by Django 5.1.6 on 2025-02-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setoo_app', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, unique=True)),
                ('drive_file_id', models.CharField(max_length=255, unique=True)),
                ('drive_folder_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, unique=True)),
                ('drive_file_id', models.CharField(max_length=255, unique=True)),
                ('drive_folder_id', models.CharField(max_length=255)),
            ],
        ),
    ]
