version: "3.9"

services:
  web:
    build:
      context: ./.devcontainer  # Tell docker-compose to use the Dockerfile in .devcontainer
      dockerfile: Dockerfile  # If your Dockerfile has a different name, specify it here
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DJANGO_SETTINGS_MODULE=your_project_name.settings # Important!
    volumes:
      - .:/app  # Mount your project directory. VERY IMPORTANT!
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"